steps:
  # 0. Pull the latest image to use as a cache for faster builds.
  # Ignore errors if the image doesn't exist yet (e.g., first build).
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest || exit 0"]

  # 1. Build the container image.
  # The Dockerfile is now configured to run unit tests during this build step.
  # If tests fail, the build will stop here.
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:main"
      # Use the latest image as a cache source to speed up builds
      - "--cache-from"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest"
      - "."

  # 2. Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:main"

  # 3. Tag the new image as 'latest' for caching in future builds
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "artifacts"
      - "docker"
      - "tags"
      - "add" # This will now ensure the 'main' tag also gets the 'latest' tag
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:main"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest"

  # Grant the Cloud Build service account the Artifact Registry Tag Editor role.
  # This is necessary for updating the 'latest' tag.
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "projects"
      - "add-iam-policy-binding"
      - "${PROJECT_ID}"
      - "--member=serviceAccount:${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
      - "--role=roles/artifactregistry.tagEditor"

  # 4. Deploy container image to Cloud Run with security best practices
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:main"
      - "--region"
      - "${_LOCATION}"
      - "--platform"
      - "managed"
      # Best Practice: Secure the service. Access should be via API Gateway.
      - "--allow-unauthenticated"
      # Set environment variables. For secrets, use Secret Manager.
      # Note: You must create secrets named 'line-channel-id' and 'line-channel-secret' in Secret Manager
      # and grant the Cloud Run service account the 'Secret Manager Secret Accessor' role.
      - "--set-secrets=LINE_CHANNEL_ID=line-channel-id:latest,LINE_CHANNEL_SECRET=line-channel-secret:latest"
      - "--project"
      - "${PROJECT_ID}"
      - "--timeout=600s" # Increase timeout to 10 minutes (default is 5 minutes)
      # Best Practice: Specify a dedicated service account for the Cloud Run service
      # - "--service-account=your-cloud-run-service-account@${PROJECT_ID}.iam.gserviceaccount.com"

images:
  - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:main"

substitutions:
  _SERVICE_NAME: "mega-care-api"
  _REPO_NAME: "mega-care-connect-repo" # The name of your Artifact Registry repo
  _LOCATION: "asia-southeast1" # The region for your services

options:
  logging: CLOUD_LOGGING_ONLY