# This Cloud Build configuration builds a Go application,
# pushes the Docker image to Artifact Registry, and deploys it to Cloud Run.

# Add this options block to fix the error
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

substitutions:
  _SERVICE_NAME: 'helloworld-service' # Default service name
  _REGION: 'asia-southeast1'          # Default region
  _ARTIFACT_REPO: 'mega-care-connect-repo'
  _IMAGE_NAME: 'mega-care-api-app'

steps:
# Step 1: Build the Docker image
# Uses the 'docker' builder to build the image from the Dockerfile in the current directory.
# The image is tagged with the project ID, repository name, and the commit SHA.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA', '.']

# Step 2: Push the Docker image to Artifact Registry
# Uses the 'docker' builder to push the tagged image to Artifact Registry.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA']

# Step 3: Deploy the container image to Cloud Run
# Uses the 'gcloud' builder to deploy the image to a Cloud Run service.
# The --allow-unauthenticated flag makes the service publicly accessible.
# Remove it if you need authentication.
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'
    - '--region'
    - '${_REGION}'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
# This specifies the image that will be built and pushed.
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:$COMMIT_SHA'