steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "."

  # 2. Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"

  # 3. Deploy container image to Cloud Run
  - name: "gcr.io/google-appengine/exec-wrapper"
    args:
      - "-i"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "-s"
      - "${PROJECT_ID}:${_LOCATION}:${_SERVICE_NAME}"
      - "-e"
      - "gcloud"
      - "--"
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"
      - "--region"
      - "${_LOCATION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated" # Important for API Gateway integration
      - "--project"
      - "${PROJECT_ID}"

images:
  - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}"

substitutions:
  _SERVICE_NAME: "mega-care-api"
  _REPO_NAME: "mega-care-api-repo" # The name of your Artifact Registry repo
  _LOCATION: "asia-southeast1" # The region for your services

options:
  logging: CLOUD_LOGGING_ONLY